version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: always
    environment:
      APP_DIR: data/app
      PSQL_HOST: psql
      PSQL_PORT: 5432
      PSQL_DATABASE: postgres
      PSQL_USER: postgres
      PSQL_PASS: postgres
      NODE_OPTIONS: --max_old_space_size=2048
    depends_on:
      - psql
    volumes:
      - ./:/home/app/
  psql:
    restart: always
    image: "postgres:10.5"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/psql:/var/lib/postgresql/data
