version: "3"

services:
  app:
    build: .
    restart: always
    environment: []
    #env_file: .env
    depends_on:
      - psql
    volumes:
      - ./:/home/app
  psql:
    restart: always
    image: "postgres:10.5"
    volumes:
      - ./data/psql:/var/lib/postgresql/data
